In [75]:
import numpy as np
from scipy.signal import convolve2d 

In [5]:

# Given theta in degrees
theta = 90

# Convert degrees to radians
theta_radians = np.radians(theta)
print("theta_radians is ", theta_radians)

# Compute cosine value
cos_theta = np.cos(theta_radians)

print(f"cos({theta}) = {cos_theta}")

theta_radians is  1.5707963267948966
cos(90) = 6.123233995736766e-17


In [7]:
theta = 90
cos_theta = np.cos(np.radians(theta))  # Convert degrees to radians before using np.cos
print(f"cos({theta}) = {cos_theta}")

cos(90) = 6.123233995736766e-17


In [15]:
# Given vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vector addition
result = np.dot(a,b)

print(f"The sum of vectors a and b is: {result}")

The sum of vectors a and b is: 32


In [17]:
result = np.cross(a,b)
print(f"The cross of vectors a and b is: {result}")

The cross of vectors a and b is: [-3  6 -3]


In [37]:
matrix = [[2, 3, 1], [4, 5, 6], [7, 8, 9]]
matrix = np.array([matrix])
matrix

array([[[2, 3, 1],
        [4, 5, 6],
        [7, 8, 9]]])

In [39]:
inv_matrix = np.linalg.inv(matrix)

In [41]:
np.round(inv_matrix, 4)

array([[[-0.3333, -2.1111,  1.4444],
        [ 0.6667,  1.2222, -0.8889],
        [-0.3333,  0.5556, -0.2222]]])

In [43]:
contracted_tensor = np.einsum('ijk->ij', inv_matrix)
contracted_tensor

array([[-1.,  1.,  0.]])

In [51]:
def compute_eigenvalues(matrix):
    matrix = np.array(matrix, dtype=np.float64)
    eigenvalues = np.linalg.eigvals(matrix)
    return eigenvalues

# Example matrix
matrix = [[4, -2], 
          [1, 1]]

# Compute eigenvalues
eigenvalues = compute_eigenvalues(matrix)
print("Eigenvalues of the given matrix:")
print(eigenvalues)

Eigenvalues of the given matrix:
[3. 2.]


In [53]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues of the given matrix:")
print(eigenvalues)

print("\nEigenvectors of the given matrix:")
print(eigenvectors)

Eigenvalues of the given matrix:
[3. 2.]

Eigenvectors of the given matrix:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [65]:
weight = [120, 125, 125, 135, 145]
height = [61, 60, 64, 67, 72]
sample = np.array([weight, height])
np.cov(sample, bias = False)

array([[100.  ,  46.25],
       [ 46.25,  23.7 ]])

In [91]:

input_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
kernel = np.array([[1,-1], [-1,1]])
result = convolve2d(input_matrix, kernel, mode='valid')
result

array([[0, 0],
       [0, 0]])

In [98]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Compute covariance matrix
cov_matrix = np.cov(x, y)

In [100]:
cov_matrix

array([[ 2.5,  5. ],
       [ 5. , 10. ]])

In [105]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [109]:
u, s, vt = np.linalg.svd(arr1)

In [111]:
u

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

In [119]:
s = np.round(s, 4)

In [121]:
s

array([16.8481,  1.0684,  0.    ])

In [115]:
vt

array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]])

In [123]:
import sympy as sp

In [125]:
x, y = sp.symbols('x y')

In [127]:
f1 = x**2 + y**2

In [131]:
sp.diff(f1, x)

2*x

In [133]:
sp.diff(f1, y)

2*y