## Anonymous Functions

In [9]:
mlist = [1,3,5,7,9]
mobj = map(lambda m:m*100, mlist)
list(mobj)

[100, 300, 500, 700, 900]

In [11]:
marks1 = [44,44,44,67]
marks2 = [44,44,44,67]
marks3 = [44,44,44,67]
mobj = map(lambda m1,m2,m3 : m1+m2+m3, marks1, marks2, marks3)
print(list(mobj))

[132, 132, 132, 201]


## List Comprehension

In [18]:
# Given list of numbers, create a list of square of numbers

nmlist = [1,2,3,4,5]
sqlist = []

for n in nmlist :
    r = n * n
    sqlist.append(r)
print(sqlist)

[1, 4, 9, 16, 25]


In [20]:
nmlist = [1,2,3,4,5]
sqlist = [n**2 for n in nmlist]
print(sqlist)

[1, 4, 9, 16, 25]


In [26]:
# Given list of numbers, create a list of square of numbers and cube

nmlist = [1,2,3,4,5]
rlist = []

for n in nmlist :
    if(n % 2 == 0) :
        r = n * n
    else :
        r = n ** 3
    rlist.append(r)
print(rlist)

[1, 4, 27, 16, 125]


In [28]:
nmlist = [1,2,3,4,5]
sqlist = [n**2 if(n % 2 == 0) else n**3 for n in nmlist]
print(sqlist)

[1, 4, 27, 16, 125]


In [36]:
# Have even and odd numbers seperately
nmlist = [1,2,3,4,5]
evenlist = []

for n in nmlist :
    if(n % 2 == 0) :
        evenlist.append(n)
print(evenlist)

evenlist1 = [n*1 for n in nmlist if n%2 == 0]
print(evenlist1)




[2, 4]
[2, 4]


In [38]:
tlist = [23,435,54]
tflist = [(t,'C') if t<30 else (t, 'M') if t>30 and t<60 else (t,'H') for t in tlist]
print (tflist)

[(23, 'C'), (435, 'H'), (54, 'M')]


In [42]:
ulist = ['u1', 'u2', 'u3']
plist = ['p1', 'p2', 'p3']
uplist = [(u,p) for u in ulist for p in plist]
print(uplist)

[('u1', 'p1'), ('u1', 'p2'), ('u1', 'p3'), ('u2', 'p1'), ('u2', 'p2'), ('u2', 'p3'), ('u3', 'p1'), ('u3', 'p2'), ('u3', 'p3')]


In [48]:
ulist = ['u1', 'u2', 'u3']
plist = ['p1', 'p2', 'p3']
uplist = [(u,p) for u in ulist if u!='u2' for p in plist if p!='p3']
print(uplist)

[('u1', 'p1'), ('u1', 'p2'), ('u3', 'p1'), ('u3', 'p2')]


### Scope

In [89]:
g1 = 111;
g2 = 222;
v3 = 555
v4 = 666
def mf99(v3) :
    global g2
    v4 = 444
    g2 = 111111111
    print('debug2', g1,g2,v3,v4)
    print('locals', locals())

print('debug1',g1,g2)
mf99(333)
print('debug2', g1,g2,v3,v4)

debug1 111 222
debug2 111 111111111 333 444
locals {'v3': 333, 'v4': 444}
debug2 111 111111111 555 666


## Recursion

In [100]:
def factorial(n):
    if(n < 0) :
        print("Boss don't enter negative numbers")
        return
    if(n ==0) :
        return 1;
    return n * factorial(n-1)

x = factorial(-2)
print(x)


Boss don't enter negative numbers
None


# NUMPY

In [105]:
import numpy as np

In [131]:
# Single dimensional array
mylist1 = [10,20,30,40,50]
n1 = np.array(mylist1, dtype = np.int8)
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.size)
print(n1.itemsize) # in bytes
print(n1.dtype)
print(n1)

<class 'numpy.ndarray'>
1
(5,)
5
1
int8
[10 20 30 40 50]


In [138]:
# Two dimensional array
mylist1 = [[10,20, 30],[40,50,60]]
n1 = np.array(mylist1, dtype = np.int8)
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.size)
print(n1.itemsize) # in bytes
print(n1.dtype)
print(n1)

<class 'numpy.ndarray'>
2
(2, 3)
6
1
int8
[[10 20 30]
 [40 50 60]]


In [140]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.arange(10,19) # Always return a one dimensional array

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [144]:
np.arange(10.1,20.9,2.3)

array([10.1, 12.4, 14.7, 17. , 19.3])

In [154]:
n64 = np.arange(24).reshape(6,4)
print(n64)
print(np.shape(n64))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(6, 4)


In [174]:
n6 = np.arange(6)
print (n6)
print(n6.reshape(1,6))

[0 1 2 3 4 5]
[[0 1 2 3 4 5]]


In [180]:
np.arange(2048).reshape(-1,8)


array([[   0,    1,    2, ...,    5,    6,    7],
       [   8,    9,   10, ...,   13,   14,   15],
       [  16,   17,   18, ...,   21,   22,   23],
       ...,
       [2024, 2025, 2026, ..., 2029, 2030, 2031],
       [2032, 2033, 2034, ..., 2037, 2038, 2039],
       [2040, 2041, 2042, ..., 2045, 2046, 2047]])

In [256]:
np.random.seed(0)
n64 = np.random.randint(low=10, high=100, size=(6,4))
n64

array([[54, 57, 74, 77],
       [77, 19, 93, 31],
       [46, 97, 80, 98],
       [98, 22, 68, 75],
       [49, 97, 56, 98],
       [91, 47, 35, 87]])

In [258]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [262]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [266]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

## Extraction

In [271]:

c23 = np.random.randint(low=10, high = 100, size=(8,9))
c23

array([[82, 19, 30, 90, 79, 89, 57, 74, 92],
       [98, 59, 39, 29, 29, 24, 49, 42, 75],
       [19, 67, 42, 41, 84, 33, 45, 85, 65],
       [38, 44, 10, 10, 46, 63, 15, 48, 27],
       [89, 14, 52, 68, 41, 11, 75, 51, 67],
       [45, 21, 56, 92, 10, 24, 63, 22, 52],
       [94, 85, 78, 16, 78, 57, 13, 86, 62],
       [88, 25, 30, 68, 33, 89, 23, 95, 58]])

In [283]:
c23[1::2]

array([[98, 59, 39, 29, 29, 24, 49, 42, 75],
       [38, 44, 10, 10, 46, 63, 15, 48, 27],
       [45, 21, 56, 92, 10, 24, 63, 22, 52],
       [88, 25, 30, 68, 33, 89, 23, 95, 58]])

In [293]:
c23[2:6, 2:6]

array([[42, 41, 84, 33],
       [10, 10, 46, 63],
       [52, 68, 41, 11],
       [56, 92, 10, 24]])

In [295]:
c23[[0,1,-1,-2]]

array([[82, 19, 30, 90, 79, 89, 57, 74, 92],
       [98, 59, 39, 29, 29, 24, 49, 42, 75],
       [88, 25, 30, 68, 33, 89, 23, 95, 58],
       [94, 85, 78, 16, 78, 57, 13, 86, 62]])

In [297]:
len(c23)

8

In [299]:
c23[[0,1,len(c23)-2,len(c23)-1]]

array([[82, 19, 30, 90, 79, 89, 57, 74, 92],
       [98, 59, 39, 29, 29, 24, 49, 42, 75],
       [94, 85, 78, 16, 78, 57, 13, 86, 62],
       [88, 25, 30, 68, 33, 89, 23, 95, 58]])

In [307]:
c23

array([[82, 19, 30, 90, 79, 89, 57, 74, 92],
       [98, 59, 39, 29, 29, 24, 49, 42, 75],
       [19, 67, 42, 41, 84, 33, 45, 85, 65],
       [38, 44, 10, 10, 46, 63, 15, 48, 27],
       [89, 14, 52, 68, 41, 11, 75, 51, 67],
       [45, 21, 56, 92, 10, 24, 63, 22, 52],
       [94, 85, 78, 16, 78, 57, 13, 86, 62],
       [88, 25, 30, 68, 33, 89, 23, 95, 58]])

In [309]:
c23[[2,3],[3,-1]]

array([41, 27])

In [311]:
c23[:, [2,4,6]]

array([[30, 79, 57],
       [39, 29, 49],
       [42, 84, 45],
       [10, 46, 15],
       [52, 41, 75],
       [56, 10, 63],
       [78, 78, 13],
       [30, 33, 23]])

In [315]:
c23[:, [5]]

array([[89],
       [24],
       [33],
       [63],
       [11],
       [24],
       [57],
       [89]])

In [317]:
c23[:, 5]

array([89, 24, 33, 63, 11, 24, 57, 89])

In [321]:
c23.shape[-1]

9

In [346]:
mask1 = [c23>50]
#print(mask1)
mask2 = [c23 % 2 == 0]
print(mask2)

[array([[ True, False,  True,  True, False, False, False,  True,  True],
       [ True, False, False, False, False,  True, False,  True, False],
       [False, False,  True, False,  True, False, False, False, False],
       [ True,  True,  True,  True,  True, False, False,  True, False],
       [False,  True,  True,  True, False, False, False, False, False],
       [False, False,  True,  True,  True,  True, False,  True,  True],
       [ True, False,  True,  True,  True, False, False,  True,  True],
       [ True, False,  True,  True, False, False, False, False,  True]])]


In [350]:
c23[(c23 % 2 == 0) & (c23>50)]

array([82, 90, 74, 92, 98, 84, 52, 68, 56, 92, 52, 94, 78, 78, 86, 62, 88,
       68, 58])

In [360]:
c23[(c23 % 2 == 0)] = 1000
print(c23)

[[1000   19 1000 1000   79   89   57 1000 1000]
 [1000   59   39   29   29 1000   49 1000   75]
 [  19   67 1000   41 1000   33   45   85   65]
 [1000 1000 1000 1000 1000   63   15 1000   27]
 [  89 1000 1000 1000   41   11   75   51   67]
 [  45   21 1000 1000 1000 1000   63 1000 1000]
 [1000   85 1000 1000 1000   57   13 1000 1000]
 [1000   25 1000 1000   33   89   23   95 1000]]
